// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 0002_classes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createClass = `-- name: CreateClass :one
INSERT INTO classes (id, created_at, updated_at, subject, grade, teacher_id)
VALUES (gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2,
        $3)
RETURNING id, subject, grade, teacher_id, created_at, updated_at
`

type CreateClassParams struct {
	Subject   string        `json:"subject"`
	Grade     int32         `json:"grade"`
	TeacherID uuid.NullUUID `json:"teacher_id"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, createClass, arg.Subject, arg.Grade, arg.TeacherID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Grade,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClasses = `-- name: GetClasses :many
SELECT id, subject, grade, teacher_id, created_at, updated_at
FROM classes
WHERE teacher_id = $1
`

func (q *Queries) GetClasses(ctx context.Context, teacherID uuid.NullUUID) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, getClasses, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Grade,
			&i.TeacherID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudents = `-- name: GetStudents :many
SELECT id, first_name, last_name, email, type, avatar, avatar_color, created_at, updated_at
FROM users
WHERE type = 'student'
`

func (q *Queries) GetStudents(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Type,
			&i.Avatar,
			&i.AvatarColor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
