// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 0002_classes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createClass = `-- name: CreateClass :one
INSERT INTO classes (id, created_at, updated_at, subject, grade, teacher_id)
VALUES (gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2,
        $3)
RETURNING id, subject, grade, teacher_id, created_at, updated_at
`

type CreateClassParams struct {
	Subject   string
	Grade     int32
	TeacherID uuid.NullUUID
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, createClass, arg.Subject, arg.Grade, arg.TeacherID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Grade,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
