// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 0003_stream.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (id, post_id, author_id, content, created_at)
VALUES (gen_random_uuid(),
        $1,
        $2,
        $3,
        NOW())
RETURNING id, post_id, author_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	PostID   uuid.NullUUID `json:"post_id"`
	AuthorID uuid.NullUUID `json:"author_id"`
	Content  string        `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.PostID, arg.AuthorID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, class_id, author_id, content, created_at)
VALUES (gen_random_uuid(),
        $1,
        $2,
        $3,
        NOW())
RETURNING id, class_id, author_id, parent_id, content, created_at, updated_at
`

type CreatePostParams struct {
	ClassID  uuid.NullUUID `json:"class_id"`
	AuthorID uuid.NullUUID `json:"author_id"`
	Content  string        `json:"content"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.ClassID, arg.AuthorID, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.AuthorID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE
FROM comments
WHERE id = $1
  AND author_id = $2
`

type DeleteCommentParams struct {
	ID       uuid.UUID     `json:"id"`
	AuthorID uuid.NullUUID `json:"author_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.ExecContext(ctx, deleteComment, arg.ID, arg.AuthorID)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE
FROM posts
WHERE id = $1
  AND author_id = $2
`

type DeletePostParams struct {
	ID       uuid.UUID     `json:"id"`
	AuthorID uuid.NullUUID `json:"author_id"`
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.ExecContext(ctx, deletePost, arg.ID, arg.AuthorID)
	return err
}

const getCommentsByPost = `-- name: GetCommentsByPost :many
SELECT c.id, c.post_id, c.author_id, c.content, c.created_at, c.updated_at,
       u.first_name,
       u.last_name
FROM comments c
         JOIN users u ON u.id = c.author_id
WHERE c.post_id = $1
ORDER BY c.created_at
`

type GetCommentsByPostRow struct {
	ID        uuid.UUID     `json:"id"`
	PostID    uuid.NullUUID `json:"post_id"`
	AuthorID  uuid.NullUUID `json:"author_id"`
	Content   string        `json:"content"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
	FirstName string        `json:"first_name"`
	LastName  string        `json:"last_name"`
}

func (q *Queries) GetCommentsByPost(ctx context.Context, postID uuid.NullUUID) ([]GetCommentsByPostRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByPostRow
	for rows.Next() {
		var i GetCommentsByPostRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, class_id, author_id, parent_id, content, created_at, updated_at
FROM posts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.AuthorID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostsByClass = `-- name: GetPostsByClass :many
SELECT p.id, p.class_id, p.author_id, p.parent_id, p.content, p.created_at, p.updated_at,
       u.first_name,
       u.last_name
FROM posts p
         JOIN users u ON u.id = p.author_id
WHERE p.class_id = $1
ORDER BY p.created_at DESC
`

type GetPostsByClassRow struct {
	ID        uuid.UUID     `json:"id"`
	ClassID   uuid.NullUUID `json:"class_id"`
	AuthorID  uuid.NullUUID `json:"author_id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	Content   string        `json:"content"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
	FirstName string        `json:"first_name"`
	LastName  string        `json:"last_name"`
}

func (q *Queries) GetPostsByClass(ctx context.Context, classID uuid.NullUUID) ([]GetPostsByClassRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsByClassRow
	for rows.Next() {
		var i GetPostsByClassRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.AuthorID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
