// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 0004_materials_assignments.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (
    id,
    type,
    title,
    class_id,
    details,
    assign_date,
    due_date,
    attachment_count,
    created_at,
    updated_at
)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    NOW(),
    $5,
    $6,
    NOW(),
    NOW()
)
RETURNING id, type, title, class_id, details, assign_date, due_date, attachment_count, created_at, updated_at
`

type CreateAssignmentParams struct {
	Type            ContentType    `json:"type"`
	Title           string         `json:"title"`
	ClassID         uuid.NullUUID  `json:"class_id"`
	Details         sql.NullString `json:"details"`
	DueDate         sql.NullTime   `json:"due_date"`
	AttachmentCount sql.NullInt32  `json:"attachment_count"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, createAssignment,
		arg.Type,
		arg.Title,
		arg.ClassID,
		arg.Details,
		arg.DueDate,
		arg.AttachmentCount,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.ClassID,
		&i.Details,
		&i.AssignDate,
		&i.DueDate,
		&i.AttachmentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserAssignmentsForClass = `-- name: CreateUserAssignmentsForClass :exec
INSERT INTO user_assignments (
    id,
    assignment_id,
    student_id,
    status,
    created_at,
    updated_at
)
SELECT
    gen_random_uuid(),
    $1,
    e.student_id,
    'assigned',
    NOW(),
    NOW()
FROM class_enrollments e
WHERE e.class_id = $2
ON CONFLICT (assignment_id, student_id) DO NOTHING
`

type CreateUserAssignmentsForClassParams struct {
	AssignmentID uuid.NullUUID `json:"assignment_id"`
	ClassID      uuid.UUID     `json:"class_id"`
}

func (q *Queries) CreateUserAssignmentsForClass(ctx context.Context, arg CreateUserAssignmentsForClassParams) error {
	_, err := q.db.ExecContext(ctx, createUserAssignmentsForClass, arg.AssignmentID, arg.ClassID)
	return err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE
FROM assignments
WHERE id = $1
`

func (q *Queries) DeleteAssignment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAssignment, id)
	return err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, type, title, class_id, details, assign_date, due_date, attachment_count, created_at, updated_at
FROM assignments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAssignmentByID(ctx context.Context, id uuid.UUID) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, getAssignmentByID, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.ClassID,
		&i.Details,
		&i.AssignDate,
		&i.DueDate,
		&i.AttachmentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentSubmissions = `-- name: GetAssignmentSubmissions :many
SELECT
    ua.id,
    ua.assignment_id,
    ua.student_id,
    ua.grade,
    ua.status,
    ua.submission_text,
    ua.feedback,
    ua.submitted_at,
    ua.created_at,
    ua.updated_at,
    u.first_name,
    u.last_name,
    u.email,
    u.grade AS student_grade
FROM user_assignments ua
JOIN users u ON u.id = ua.student_id
WHERE ua.assignment_id = $1
ORDER BY u.last_name, u.first_name
`

type GetAssignmentSubmissionsRow struct {
	ID             uuid.UUID        `json:"id"`
	AssignmentID   uuid.NullUUID    `json:"assignment_id"`
	StudentID      uuid.NullUUID    `json:"student_id"`
	Grade          sql.NullInt32    `json:"grade"`
	Status         AssignmentStatus `json:"status"`
	SubmissionText sql.NullString   `json:"submission_text"`
	Feedback       sql.NullString   `json:"feedback"`
	SubmittedAt    sql.NullTime     `json:"submitted_at"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      sql.NullTime     `json:"updated_at"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	StudentGrade   sql.NullInt32    `json:"student_grade"`
}

func (q *Queries) GetAssignmentSubmissions(ctx context.Context, assignmentID uuid.NullUUID) ([]GetAssignmentSubmissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentSubmissions, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssignmentSubmissionsRow
	for rows.Next() {
		var i GetAssignmentSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.StudentID,
			&i.Grade,
			&i.Status,
			&i.SubmissionText,
			&i.Feedback,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.StudentGrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassAssignments = `-- name: GetClassAssignments :many
SELECT id, type, title, class_id, details, assign_date, due_date, attachment_count, created_at, updated_at
FROM assignments
WHERE class_id = $1
ORDER BY COALESCE(due_date, assign_date, created_at) DESC
`

func (q *Queries) GetClassAssignments(ctx context.Context, classID uuid.NullUUID) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, getClassAssignments, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.ClassID,
			&i.Details,
			&i.AssignDate,
			&i.DueDate,
			&i.AttachmentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassGradebook = `-- name: GetClassGradebook :many
SELECT
    a.id AS assignment_id,
    a.title,
    a.due_date,
    ua.id AS user_assignment_id,
    ua.student_id,
    ua.grade,
    ua.status,
    ua.feedback,
    ua.submitted_at,
    u.first_name,
    u.last_name,
    u.email
FROM assignments a
JOIN user_assignments ua ON ua.assignment_id = a.id
JOIN users u ON u.id = ua.student_id
WHERE a.class_id = $1
  AND a.type = 'assignment'
ORDER BY a.due_date NULLS LAST, a.created_at, u.last_name, u.first_name
`

type GetClassGradebookRow struct {
	AssignmentID     uuid.UUID        `json:"assignment_id"`
	Title            string           `json:"title"`
	DueDate          sql.NullTime     `json:"due_date"`
	UserAssignmentID uuid.UUID        `json:"user_assignment_id"`
	StudentID        uuid.NullUUID    `json:"student_id"`
	Grade            sql.NullInt32    `json:"grade"`
	Status           AssignmentStatus `json:"status"`
	Feedback         sql.NullString   `json:"feedback"`
	SubmittedAt      sql.NullTime     `json:"submitted_at"`
	FirstName        string           `json:"first_name"`
	LastName         string           `json:"last_name"`
	Email            string           `json:"email"`
}

func (q *Queries) GetClassGradebook(ctx context.Context, classID uuid.NullUUID) ([]GetClassGradebookRow, error) {
	rows, err := q.db.QueryContext(ctx, getClassGradebook, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClassGradebookRow
	for rows.Next() {
		var i GetClassGradebookRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.Title,
			&i.DueDate,
			&i.UserAssignmentID,
			&i.StudentID,
			&i.Grade,
			&i.Status,
			&i.Feedback,
			&i.SubmittedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentUserAssignment = `-- name: GetStudentUserAssignment :one
SELECT id, assignment_id, student_id, grade, status, submission_text, feedback, submitted_at, created_at, updated_at
FROM user_assignments
WHERE assignment_id = $1
  AND student_id = $2
LIMIT 1
`

type GetStudentUserAssignmentParams struct {
	AssignmentID uuid.NullUUID `json:"assignment_id"`
	StudentID    uuid.NullUUID `json:"student_id"`
}

func (q *Queries) GetStudentUserAssignment(ctx context.Context, arg GetStudentUserAssignmentParams) (UserAssignment, error) {
	row := q.db.QueryRowContext(ctx, getStudentUserAssignment, arg.AssignmentID, arg.StudentID)
	var i UserAssignment
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Grade,
		&i.Status,
		&i.SubmissionText,
		&i.Feedback,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAssignmentByID = `-- name: GetUserAssignmentByID :one
SELECT id, assignment_id, student_id, grade, status, submission_text, feedback, submitted_at, created_at, updated_at
FROM user_assignments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserAssignmentByID(ctx context.Context, id uuid.UUID) (UserAssignment, error) {
	row := q.db.QueryRowContext(ctx, getUserAssignmentByID, id)
	var i UserAssignment
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Grade,
		&i.Status,
		&i.SubmissionText,
		&i.Feedback,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const gradeUserAssignment = `-- name: GradeUserAssignment :one
UPDATE user_assignments
SET grade = $1,
    feedback = $2,
    status = 'graded',
    updated_at = NOW()
WHERE id = $3
RETURNING id, assignment_id, student_id, grade, status, submission_text, feedback, submitted_at, created_at, updated_at
`

type GradeUserAssignmentParams struct {
	Grade    sql.NullInt32  `json:"grade"`
	Feedback sql.NullString `json:"feedback"`
	ID       uuid.UUID      `json:"id"`
}

func (q *Queries) GradeUserAssignment(ctx context.Context, arg GradeUserAssignmentParams) (UserAssignment, error) {
	row := q.db.QueryRowContext(ctx, gradeUserAssignment, arg.Grade, arg.Feedback, arg.ID)
	var i UserAssignment
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Grade,
		&i.Status,
		&i.SubmissionText,
		&i.Feedback,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMissingAssignments = `-- name: MarkMissingAssignments :exec
UPDATE user_assignments ua
SET status = 'missing',
    updated_at = NOW()
FROM assignments a
WHERE ua.assignment_id = a.id
  AND ua.status = 'assigned'
  AND a.type = 'assignment'
  AND a.due_date IS NOT NULL
  AND a.due_date < NOW()
`

func (q *Queries) MarkMissingAssignments(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markMissingAssignments)
	return err
}

const submitAssignment = `-- name: SubmitAssignment :one
UPDATE user_assignments
SET submission_text = $1,
    submitted_at = NOW(),
    status = 'submitted',
    updated_at = NOW()
WHERE assignment_id = $2
  AND student_id = $3
  AND status <> 'graded'
RETURNING id, assignment_id, student_id, grade, status, submission_text, feedback, submitted_at, created_at, updated_at
`

type SubmitAssignmentParams struct {
	SubmissionText sql.NullString `json:"submission_text"`
	AssignmentID   uuid.NullUUID  `json:"assignment_id"`
	StudentID      uuid.NullUUID  `json:"student_id"`
}

func (q *Queries) SubmitAssignment(ctx context.Context, arg SubmitAssignmentParams) (UserAssignment, error) {
	row := q.db.QueryRowContext(ctx, submitAssignment, arg.SubmissionText, arg.AssignmentID, arg.StudentID)
	var i UserAssignment
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Grade,
		&i.Status,
		&i.SubmissionText,
		&i.Feedback,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE assignments
SET type = $1,
    title = $2,
    details = $3,
    due_date = $4,
    attachment_count = $5,
    updated_at = NOW()
WHERE id = $6
RETURNING id, type, title, class_id, details, assign_date, due_date, attachment_count, created_at, updated_at
`

type UpdateAssignmentParams struct {
	Type            ContentType    `json:"type"`
	Title           string         `json:"title"`
	Details         sql.NullString `json:"details"`
	DueDate         sql.NullTime   `json:"due_date"`
	AttachmentCount sql.NullInt32  `json:"attachment_count"`
	ID              uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, updateAssignment,
		arg.Type,
		arg.Title,
		arg.Details,
		arg.DueDate,
		arg.AttachmentCount,
		arg.ID,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.ClassID,
		&i.Details,
		&i.AssignDate,
		&i.DueDate,
		&i.AttachmentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
