// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 0005_class_enrollments.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const enrollStudent = `-- name: EnrollStudent :one
INSERT INTO class_enrollments (id, class_id, student_id, enrolled_at)
VALUES (gen_random_uuid(), $1, $2, NOW())
ON CONFLICT (class_id, student_id) DO NOTHING
RETURNING id, class_id, student_id, enrolled_at
`

type EnrollStudentParams struct {
	ClassID   uuid.UUID `json:"class_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) EnrollStudent(ctx context.Context, arg EnrollStudentParams) (ClassEnrollment, error) {
	row := q.db.QueryRowContext(ctx, enrollStudent, arg.ClassID, arg.StudentID)
	var i ClassEnrollment
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.StudentID,
		&i.EnrolledAt,
	)
	return i, err
}

const getClassStudents = `-- name: GetClassStudents :many
SELECT u.id, u.first_name, u.last_name, u.email, u.password, u.type, u.grade, u.avatar, u.avatar_color, u.created_at, u.updated_at
FROM users u
         JOIN class_enrollments e ON e.student_id = u.id
WHERE e.class_id = $1
`

func (q *Queries) GetClassStudents(ctx context.Context, classID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getClassStudents, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Password,
			&i.Type,
			&i.Grade,
			&i.Avatar,
			&i.AvatarColor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrolledStudentIDs = `-- name: GetEnrolledStudentIDs :many
SELECT student_id
FROM class_enrollments
WHERE class_id = $1
`

func (q *Queries) GetEnrolledStudentIDs(ctx context.Context, classID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getEnrolledStudentIDs, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var student_id uuid.UUID
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentClasses = `-- name: GetStudentClasses :many
SELECT c.id, c.subject, c.grade, c.teacher_id, c.color, c.created_at, c.updated_at
FROM classes c
         JOIN class_enrollments e ON e.class_id = c.id
WHERE e.student_id = $1
`

func (q *Queries) GetStudentClasses(ctx context.Context, studentID uuid.UUID) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, getStudentClasses, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Grade,
			&i.TeacherID,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isStudentEnrolled = `-- name: IsStudentEnrolled :one
SELECT EXISTS (SELECT 1
               FROM class_enrollments
               WHERE class_id = $1
                 AND student_id = $2) AS enrolled
`

type IsStudentEnrolledParams struct {
	ClassID   uuid.UUID `json:"class_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) IsStudentEnrolled(ctx context.Context, arg IsStudentEnrolledParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isStudentEnrolled, arg.ClassID, arg.StudentID)
	var enrolled bool
	err := row.Scan(&enrolled)
	return enrolled, err
}

const unenrollStudent = `-- name: UnenrollStudent :exec
DELETE
FROM class_enrollments
WHERE class_id = $1
  AND student_id = $2
`

type UnenrollStudentParams struct {
	ClassID   uuid.UUID `json:"class_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) UnenrollStudent(ctx context.Context, arg UnenrollStudentParams) error {
	_, err := q.db.ExecContext(ctx, unenrollStudent, arg.ClassID, arg.StudentID)
	return err
}
