// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AssignmentStatus string

const (
	AssignmentStatusAssigned  AssignmentStatus = "assigned"
	AssignmentStatusSubmitted AssignmentStatus = "submitted"
	AssignmentStatusGraded    AssignmentStatus = "graded"
	AssignmentStatusMissing   AssignmentStatus = "missing"
)

func (e *AssignmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssignmentStatus(s)
	case string:
		*e = AssignmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssignmentStatus: %T", src)
	}
	return nil
}

type NullAssignmentStatus struct {
	AssignmentStatus AssignmentStatus `json:"assignment_status"`
	Valid            bool             `json:"valid"` // Valid is true if AssignmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssignmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssignmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssignmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssignmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssignmentStatus), nil
}

type ContentType string

const (
	ContentTypeAssignment ContentType = "assignment"
	ContentTypeMaterial   ContentType = "material"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType `json:"content_type"`
	Valid       bool        `json:"valid"` // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type Role string

const (
	RoleTeacher Role = "teacher"
	RoleStudent Role = "student"
	RoleParent  Role = "parent"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Assignment struct {
	ID              uuid.UUID      `json:"id"`
	Type            ContentType    `json:"type"`
	Title           string         `json:"title"`
	ClassID         uuid.NullUUID  `json:"class_id"`
	Details         sql.NullString `json:"details"`
	AssignDate      sql.NullTime   `json:"assign_date"`
	DueDate         sql.NullTime   `json:"due_date"`
	AttachmentCount sql.NullInt32  `json:"attachment_count"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type Class struct {
	ID        uuid.UUID     `json:"id"`
	Subject   string        `json:"subject"`
	Grade     int32         `json:"grade"`
	TeacherID uuid.NullUUID `json:"teacher_id"`
	Color     string        `json:"color"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type ClassEnrollment struct {
	ID         uuid.UUID `json:"id"`
	ClassID    uuid.UUID `json:"class_id"`
	StudentID  uuid.UUID `json:"student_id"`
	EnrolledAt time.Time `json:"enrolled_at"`
}

type Comment struct {
	ID        uuid.UUID     `json:"id"`
	PostID    uuid.NullUUID `json:"post_id"`
	AuthorID  uuid.NullUUID `json:"author_id"`
	Content   string        `json:"content"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type Post struct {
	ID        uuid.UUID     `json:"id"`
	ClassID   uuid.NullUUID `json:"class_id"`
	AuthorID  uuid.NullUUID `json:"author_id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	Content   string        `json:"content"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type Topic struct {
	ID           uuid.UUID     `json:"id"`
	Name         string        `json:"name"`
	AssignmentID uuid.NullUUID `json:"assignment_id"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	Email       string         `json:"email"`
	Password    sql.NullString `json:"password"`
	Type        Role           `json:"type"`
	Grade       sql.NullInt32  `json:"grade"`
	Avatar      sql.NullString `json:"avatar"`
	AvatarColor sql.NullString `json:"avatar_color"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type UserAssignment struct {
	ID             uuid.UUID        `json:"id"`
	AssignmentID   uuid.NullUUID    `json:"assignment_id"`
	StudentID      uuid.NullUUID    `json:"student_id"`
	Grade          sql.NullInt32    `json:"grade"`
	Status         AssignmentStatus `json:"status"`
	SubmissionText sql.NullString   `json:"submission_text"`
	Feedback       sql.NullString   `json:"feedback"`
	SubmittedAt    sql.NullTime     `json:"submitted_at"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      sql.NullTime     `json:"updated_at"`
}
