// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AssignmentStatus string

const (
	AssignmentStatusAssigned  AssignmentStatus = "assigned"
	AssignmentStatusSubmitted AssignmentStatus = "submitted"
	AssignmentStatusGraded    AssignmentStatus = "graded"
	AssignmentStatusMissing   AssignmentStatus = "missing"
)

func (e *AssignmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssignmentStatus(s)
	case string:
		*e = AssignmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssignmentStatus: %T", src)
	}
	return nil
}

type NullAssignmentStatus struct {
	AssignmentStatus AssignmentStatus
	Valid            bool // Valid is true if AssignmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssignmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssignmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssignmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssignmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssignmentStatus), nil
}

type ContentType string

const (
	ContentTypeAssignment ContentType = "assignment"
	ContentTypeMaterial   ContentType = "material"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType
	Valid       bool // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type Role string

const (
	RoleTeacher Role = "teacher"
	RoleStudent Role = "student"
	RoleParent  Role = "parent"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role
	Valid bool // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Assignment struct {
	ID              uuid.UUID
	Type            ContentType
	Title           string
	ClassID         uuid.NullUUID
	Details         sql.NullString
	AssignDate      sql.NullTime
	DueDate         sql.NullTime
	AttachmentCount sql.NullInt32
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
}

type Class struct {
	ID        uuid.UUID
	Subject   string
	Grade     int32
	TeacherID uuid.NullUUID
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type Comment struct {
	ID        uuid.UUID
	PostID    uuid.NullUUID
	AuthorID  uuid.NullUUID
	Content   string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type Post struct {
	ID        uuid.UUID
	AuthorID  uuid.NullUUID
	ParentID  uuid.NullUUID
	Content   string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type Topic struct {
	ID           uuid.UUID
	Name         string
	AssignmentID uuid.NullUUID
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
}

type User struct {
	ID          uuid.UUID
	FirstName   string
	LastName    string
	Email       string
	Type        Role
	Avatar      sql.NullString
	AvatarColor sql.NullString
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

type UserAssignment struct {
	ID           uuid.UUID
	AssignmentID uuid.NullUUID
	StudentID    uuid.NullUUID
	Grade        sql.NullInt32
	Status       AssignmentStatus
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
}
