### Get request
GET http://localhost:8080/home
Accept: application/json


### another get request
GET http://localhost:8080/v1
Accept: application/json



### POST request
POST http://localhost:8080/api/v1/classes/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsdW0tbG1zIiwic3ViIjoiYWNkNGExMzQtZGM4Yy00OWJjLTliMTAtMmM5Y2I3YjBhNTI4IiwiZXhwIjoxNzc3OTIwMjQ1LCJpYXQiOjE3Nzc5MTY2NDV9.RDmj_ER-B4zGfc7xDA5twce6dMT3x1SlRsTOPDJmz3I

{
  "subject": "English",
  "grade": 4,
  "teacher_id": "af282865-19c1-417f-ae18-064b30f9a3a1"
}

### GET request
GET http://localhost:8080/api/v1/classes
Accept: application/json

### GET request
GET http://localhost:8080/health
Accept: application/json

### GET request
GET http://localhost:8080/api/v1/users
Accept: application/json

### LOGIN
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

### User health
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "first_name": "mister",
  "last_name": "baker",
  "password": "12345678",
  "type": "teacher"
}

### create student
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "first_name": "Thomas",
  "last_name": "Thunderwalker",
  "email": "student@test.com",
  "password": "password123",
  "type": "student",
  "grade": 5
}

### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "12345678"
}

### get all class students
GET http://localhost:8080/api/v1/classes/f96f5b72-650e-4b6e-a68a-f0d24ca0825f/students
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsdW0tbG1zIiwic3ViIjoiMzZkMTdiYzctZGMzZi00MDAwLTkyMDEtODViNmIzYTk0NWUzIiwiZXhwIjoxNzgxNjI0MjU5LCJpYXQiOjE3ODE1Mzc4NTl9.JIbMEqnFHBlXDC2t3uUOk7kWS3I8REgClfm_7l1NDb0